kind: ConfigMap
apiVersion: v1

metadata:
  name: easyshop-config
  namespace: easyshop

data:
  MONGODB_URI: "mongodb://mongodb-service:27017/easyshop"
  NODE_ENV: "production"
  NEXT_PUBLIC_API_URL: "http://3.248.233.132.nip.io:3000"
  NEXTAUTH_URL: "http://3.248.233.132.nip.io:3000"
  NEXTAUTH_SECRET: "iJ5nPlJBVPKiPjRmS14L5WqlTiqdEAcJ42DqhbOQs2I="
  JWT_SECRET: "6aa69881f05e50d7ec317d6cecc8fef6264582dfdb52b2a49fdf8816405a107e"
