kind: ConfigMap
apiVersion: v1

metadata:
  name: easyshop-config
  namespace: easyshop

data:
  MONGODB_URI: "mongodb://mongodb-service:27017/easyshop"
  NODE_ENV: "production"
  NEXT_PUBLIC_API_URL: "http://3.250.108.246/api"
  NEXT_AUTH_URI: "http://3.250.108.246"
  NEXT_AUTH_SECRET: "dPvf+xBf05+MKta62o08w1q8DxPIMXFQxVMFBNjkzQc="
  JWT_SECRET: "b1ae17dacc2bdc86ff5e200657cb268b03cefcc174945aa4f66ca2973a28b8ab"
