kind: Secret
apiVersion: v1

metadata:
  name: easyshop-secrets
  namespace: easyshop
type: Opaque
stringData:
  JWT_SECRET: "b1ae17dacc2bdc86ff5e200657cb268b03cefcc174945aa4f66ca2973a28b8ab"
  NEXTAUTH_SECRET: "dPvf+xBf05+MKta62o08w1q8DxPIMXFQxVMFBNjkzQc="
