kind: Secret
apiVersion: v1

metadata:
  name: easyshop-secrets
  namespace: easyshop
type: Opaque
stringData:
  JWT_SECRET: "6aa69881f05e50d7ec317d6cecc8fef6264582dfdb52b2a49fdf8816405a107e"
  NEXTAUTH_SECRET: "iJ5nPlJBVPKiPjRmS14L5WqlTiqdEAcJ42DqhbOQs2I="
